import streamlit as st
import matplotlib.pyplot as plt

# =========================================================
# JEDEC Reference (Condensed, authoritative)
# =========================================================
JEDEC_MASTER = {
    "DENSITY": {
        "8Gb": {"tRFC": 350, "tREFI": 7.8, "BG": 4, "Banks": 16, "Rows": "A0–A14", "Cols": "A0–A9", "Page": "1KB"},
        "16Gb": {"tRFC": 550, "tREFI": 7.8, "BG": 4, "Banks": 16, "Rows": "A0–A15", "Cols": "A0–A9", "Page": "2KB"},
    },
    "SPEED": {
        "3200": {"tCK": 0.625, "tAA": 13.75, "tRCD": 13.75, "tRP": 13.75, "tRAS": 32},
    },
    "POWER": {
        "VDD": "1.2V ± 0.06V",
        "VPP": "2.5V ± 0.125V"
    }
}

# =========================================================
# Hard-coded Vendor Datasheets (Representative)
# =========================================================
DDR4_PARTS = {
    "Micron MT40A1G8SA-075E": {
        "Vendor": "Micron",
        "Density": "8Gb",
        "Speed": "3200",
        "Temp": "0–85°C"
    },
    "Samsung K4A8G085WB-BCRC": {
        "Vendor": "Samsung",
        "Density": "8Gb",
        "Speed": "3200",
        "Temp": "0–85°C"
    },
    "SK Hynix H5AN8G8NCJR": {
        "Vendor": "SK Hynix",
        "Density": "8Gb",
        "Speed": "3200",
        "Temp": "0–85°C"
    }
}

# =========================================================
# Page Setup
# =========================================================
st.set_page_config(page_title="DDR4 JEDEC Review Tool", layout="wide")

st.title("🛡️ DDR4 Datasheet Review & JEDEC Audit Tool")

st.info(
    "If you like the results generated by this tool, you can download the full code package "
    "and run it locally on your PC. This allows you to review **your own private datasheets** "
    "without uploading them to any public server."
)

# =========================================================
# Sidebar Selection
# =========================================================
st.sidebar.header("Select DDR4 Part")
selected_part = st.sidebar.radio("Available Parts", list(DDR4_PARTS.keys()))

part = DDR4_PARTS[selected_part]
density_ref = JEDEC_MASTER["DENSITY"][part["Density"]]
speed_ref = JEDEC_MASTER["SPEED"][part["Speed"]]

st.success(f"🔍 Currently reviewing: **{selected_part} ({part['Vendor']})**")

# =========================================================
# Tabs
# =========================================================
tabs = st.tabs([
    "1. DDR Basics",
    "2. Clock & Frequency",
    "3. Addressing & Architecture",
    "4. Power & Voltages",
    "5. AC Timing",
    "6. Training",
    "7. Refresh / Thermal",
    "8. Signal Integrity",
    "9. DDR3 vs DDR4 vs DDR5",
    "10. Review Summary"
])

# =========================================================
# TAB 1 – DDR BASICS
# =========================================================
with tabs[0]:
    st.subheader("DDR Basics")

    st.markdown("**What this tab is:**")
    st.markdown("Foundational overview of DDR4 architecture and internal operation.")

    st.markdown("**Why it matters:**")
    st.markdown(
        "All timing, refresh, and bandwidth behavior stems from these fundamentals. "
        "Misunderstanding basics leads to incorrect controller configuration."
    )

    st.table([
        {"Parameter": "Memory Type", "Value": "DDR4 SDRAM"},
        {"Parameter": "Prefetch", "Value": "8n"},
        {"Parameter": "Bank Groups", "Value": density_ref["BG"]},
        {"Parameter": "Total Banks", "Value": density_ref["Banks"]},
        {"Parameter": "Page Size", "Value": density_ref["Page"]}
    ])

    st.markdown("**Reviewer insights / Q&A:**")
    st.markdown("""
**Q: What is DDR?**  
A: DDR transfers data on both clock edges, doubling effective bandwidth.

**Q: Why does DDR4 use bank groups?**  
A: To increase parallelism but at the cost of stricter timing rules.

**Cause → Effect → Symptom:**  
Incorrect bank mapping → timing overlap → intermittent field failures.

**Mitigation:**  
Ensure controller configuration exactly matches JEDEC architecture.
""")

# =========================================================
# TAB 2 – CLOCK & FREQUENCY
# =========================================================
with tabs[1]:
    st.subheader("Clock & Frequency")

    st.markdown("**What this tab is:**")
    st.markdown("Validation of speed bin, clock period, and timing reference.")

    st.markdown("**Why it matters:**")
    st.markdown("Clock defines all DDR timing margins. Errors propagate system-wide.")

    st.table([
        {"Metric": "Data Rate", "Value": "3200 MT/s"},
        {"Metric": "tCK", "Value": f"{speed_ref['tCK']} ns"},
    ])

    st.markdown("**Reviewer insights / Q&A:**")
    st.markdown("""
**Q: Why does higher speed increase risk?**  
A: Reduced setup/hold margins amplify SI and power noise sensitivity.

**Mitigation:**  
Increase CAS latency or downgrade speed grade.
""")

# =========================================================
# TAB 3 – ADDRESSING
# =========================================================
with tabs[2]:
    st.subheader("Addressing & Architecture")

    st.markdown("**What this tab is:**")
    st.markdown("Logical-to-physical memory mapping verification.")

    st.markdown("**Why it matters:**")
    st.markdown("Incorrect addressing causes silent data corruption.")

    st.table([
        {"Field": "Rows", "Value": density_ref["Rows"]},
        {"Field": "Columns", "Value": density_ref["Cols"]},
        {"Field": "Banks", "Value": density_ref["Banks"]}
    ])

    st.markdown("**Reviewer insights:**")
    st.markdown("""
Address errors often pass initial tests but fail long-term retention.
""")

# =========================================================
# TAB 4 – POWER
# =========================================================
with tabs[3]:
    st.subheader("Power & Voltages")

    st.markdown("**What this tab is:**")
    st.markdown("Supply voltage compliance review.")

    st.markdown("**Why it matters:**")
    st.markdown("Voltage margin directly impacts timing and reliability.")

    st.table([
        {"Rail": "VDD", "JEDEC": JEDEC_MASTER["POWER"]["VDD"]},
        {"Rail": "VPP", "JEDEC": JEDEC_MASTER["POWER"]["VPP"]}
    ])

    st.markdown("**Reviewer insights:**")
    st.markdown("""
Undervoltage → read failures; overvoltage → aging and damage.
""")

# =========================================================
# TAB 5 – AC TIMING
# =========================================================
with tabs[4]:
    st.subheader("AC Timing")

    st.markdown("**What this tab is:**")
    st.markdown("Comparison of core AC timing parameters.")

    st.markdown("**Why it matters:**")
    st.markdown("Timing violations immediately corrupt data.")

    st.table([
        {"Timing": "tAA", "Value": speed_ref["tAA"]},
        {"Timing": "tRCD", "Value": speed_ref["tRCD"]},
        {"Timing": "tRP", "Value": speed_ref["tRP"]},
        {"Timing": "tRAS", "Value": speed_ref["tRAS"]}
    ])

    st.markdown("**Reviewer insights:**")
    st.markdown("""
Tighter timings reduce margin under temperature and voltage stress.
""")

# =========================================================
# TAB 6 – TRAINING
# =========================================================
with tabs[5]:
    st.subheader("DDR Training")

    st.markdown("**What this tab is:**")
    st.markdown("Read leveling, write leveling, and VrefDQ overview.")

    st.markdown("**Why it matters:**")
    st.markdown("Training compensates for board-level variation.")

    st.markdown("**Reviewer insights:**")
    st.markdown("""
Training failures often indicate SI or power integrity problems.
""")

# =========================================================
# TAB 7 – REFRESH & THERMAL
# =========================================================
with tabs[6]:
    st.subheader("Refresh, Thermal & Bandwidth")

    st.markdown("**What this tab is:**")
    st.markdown("Refresh overhead and thermal impact evaluation.")

    st.markdown("**Why it matters:**")
    st.markdown("More refresh → less usable bandwidth.")

    refresh_tax = (density_ref["tRFC"] / (density_ref["tREFI"] * 1000)) * 100

    st.table([
        {"Metric": "tRFC (ns)", "Value": density_ref["tRFC"]},
        {"Metric": "tREFI (µs)", "Value": density_ref["tREFI"]},
        {"Metric": "Refresh Bandwidth Loss", "Value": f"{refresh_tax:.2f}%"}
    ])

    st.markdown("""
**Formula:**  
Bandwidth Loss (%) = tRFC / (tREFI × 1000) × 100

**Why we calculate this:**  
Refresh cycles block memory access and reduce throughput.
""")

    st.markdown("**Reviewer insights:**")
    st.markdown("""
High temperature doubles refresh rate → noticeable performance drop.
""")

# =========================================================
# TAB 8 – SIGNAL INTEGRITY
# =========================================================
with tabs[7]:
    st.subheader("Signal Integrity")

    st.markdown("**What this tab is:**")
    st.markdown("Assumed SI margins and risks.")

    st.markdown("**Why it matters:**")
    st.markdown("Eye closure leads to intermittent errors.")

    st.markdown("**Reviewer insights:**")
    st.markdown("""
DDR4 is far more sensitive to routing skew than DDR3.
""")

# =========================================================
# TAB 9 – DDR3 / DDR4 / DDR5
# =========================================================
with tabs[8]:
    st.subheader("DDR Generation Comparison")

    st.markdown("**What this tab is:**")
    st.markdown("Contextual comparison of DDR generations.")

    st.markdown("**Why it matters:**")
    st.markdown("Guides migration and risk assessment.")

    st.table([
        {"Type": "DDR3", "Voltage": "1.5V", "Risk": "Power"},
        {"Type": "DDR4", "Voltage": "1.2V", "Risk": "Timing"},
        {"Type": "DDR5", "Voltage": "1.1V", "Risk": "SI / PMIC"}
    ])

    st.markdown("**Reviewer insights:**")
    st.markdown("""
DDR4 balances power and complexity; DDR5 shifts risk to SI and PMIC.
""")

# =========================================================
# TAB 10 – SUMMARY
# =========================================================
with tabs[9]:
    st.subheader("Review Summary")

    st.markdown("**What this tab is:**")
    st.markdown("Executive-level assessment.")

    st.markdown("**Why it matters:**")
    st.markdown("Drives go/no-go decisions.")

    st.markdown("""
✅ Architecture: PASS  
⚠️ Signal Integrity: REVIEW  
⚠️ Refresh / Thermal: REVIEW  

**Key mitigations:**  
- Validate high-temp refresh  
- Improve PCB routing  
- Margin CAS latency
""")
